### PR TITLE
Updated Blocktype HTML Template

### PR DESCRIPTION
**Pull request by BenParizek**
Hey Adrian,

I made the form import a bit more specific and added some comments to try to help clarify what the template is doing for folks who may not have seen twig macros before.

Peace,

Ben

### CODE REVIEW

**Comment by amacneil** [comment]
Great idea commenting the template! Could you maybe shift the comments around so each comment explains each line (rather than duplicating the actual code in the comments) - I think it may be a little unclear to people why the first forms.checkBoxSelect does nothing (since it's inside a huge comment).

**Comment by BenParizek** [comment]
Hey Adrian.  Good feedback.  I've clarified the comments a bit.  Let me know your thoughts.

I know this is kinda comment overkill for a template this short, but as I was new to twig when I started using Blocks, I'm trying to answer a lot of the questions that I had right away.  It may be possible to pull some of these comments into the other templates, but I actually think the blocktypes file, while short, allows the comments to focus on the macros and import statements specifically and really clarify them.  There is probably some room to clarify some other items like setting variables and looping through content in the main template.

**Comment by amacneil** [comment]
Thanks :smiley: On an unrelated note - you need to associate all your email addresses with your Github account, so it links to your account in the commit history.

**Comment by BenParizek** [comment]
Heh. Got it. This has been my first pull request so I appreciate hearing about those little details.  Today, a long comment, tomorrow, who knows!

**Pull request merged**
